# Generated by Django 5.2.12 on 2026-03-24 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_tenantspecialty_default_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('converted', 'Converted'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('commission_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'referrals',
                'indexes': [models.Index(fields=['tenant', 'status'], name='referrals_tenant__bdf5df_idx'), models.Index(fields=['referrer', 'status'], name='referrals_referre_cefb5c_idx'), models.Index(fields=['referred'], name='referrals_referre_e2a62f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'referrer', 'referred'), name='unique_referral_per_referrer_referred_per_tenant')],
            },
        ),
    ]
