# Generated by Django 5.2.12 on 2026-04-01 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_lead'),
        ('users', '0007_goklinikuser_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='users.saasseller'),
        ),
    ]
