# Generated by Django 5.2.12 on 2026-03-23 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('tenants', '0002_tenantspecialty_default_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('consent_form', 'Consent Form'), ('prescription', 'Prescription'), ('exam', 'Exam'), ('report', 'Report'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('is_signed', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('print', 'Print'), ('download', 'Download')], max_length=20)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_access_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_access_logs', to='patients.patient')),
            ],
            options={
                'db_table': 'medical_record_access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
