# Generated by Django 5.2.12 on 2026-03-28 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicaldocument_medicalrecordaccesslog_and_more'),
        ('patients', '0002_doctorpatientassignment'),
        ('tenants', '0004_tenant_ai_assistant_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_procedimento', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_procedimento', models.DateField()),
                ('profissional_responsavel', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_procedures', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_procedures', to='tenants.tenant')),
            ],
            options={
                'db_table': 'patient_procedures',
                'ordering': ['-data_procedimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PatientProcedureImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medical_records.patientprocedure')),
            ],
            options={
                'db_table': 'patient_procedure_images',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo_url', models.URLField()),
                ('tipo_arquivo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem')], default='pdf', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_documents',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['patient', 'criado_em'], name='patient_doc_patient_7e1a54_idx'), models.Index(fields=['tenant', 'criado_em'], name='patient_doc_tenant__99c05a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_medicamento', models.CharField(max_length=255)),
                ('dosagem', models.CharField(blank=True, max_length=120)),
                ('frequencia', models.CharField(blank=True, max_length=120)),
                ('via_administracao', models.CharField(blank=True, max_length=120)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('em_uso', models.BooleanField(default=True)),
                ('possui_alergia', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'patient_medications',
                'ordering': ['-em_uso', '-data_inicio', '-criado_em'],
                'indexes': [models.Index(fields=['patient', 'em_uso'], name='patient_med_patient_4d19da_idx'), models.Index(fields=['tenant', 'criado_em'], name='patient_med_tenant__39820c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patientprocedure',
            index=models.Index(fields=['patient', 'data_procedimento'], name='patient_pro_patient_96947d_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprocedure',
            index=models.Index(fields=['tenant', 'criado_em'], name='patient_pro_tenant__cf03e3_idx'),
        ),
    ]
