# Generated by Django 5.2.12 on 2026-04-04 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificationtoken_and_more'),
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('channel', models.CharField(choices=[('push', 'Push')], default='push', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('error', 'Error'), ('skipped', 'Skipped'), ('rate_limited', 'Rate limited')], max_length=20)),
                ('event_code', models.CharField(blank=True, max_length=80)),
                ('segment', models.CharField(blank=True, max_length=80)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('data_extra', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='notificatio_tenant__e2f80e_idx'), models.Index(fields=['user', 'status', 'created_at'], name='notificatio_user_id_028cd9_idx'), models.Index(fields=['event_code', 'created_at'], name='notificatio_event_c_b78581_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'idempotency_key'), name='notification_log_unique_idempotency_per_user')],
            },
        ),
    ]
