# Generated by Django 5.2.12 on 2026-04-04 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationtemplate_notificationlog'),
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('appointment_created', 'Appointment Created'), ('reminder_before', 'Reminder Before Appointment'), ('post_op_followup', 'Post-op Follow-up')], max_length=32)),
                ('trigger_offset', models.CharField(blank=True, default='', help_text='Offset format: 24h, 7d, 30m.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_workflows', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='notifications.notificationtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_workflows', to='tenants.tenant')),
            ],
            options={
                'db_table': 'notification_workflows',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'trigger_type'], name='notificatio_tenant__eab01a_idx'), models.Index(fields=['tenant', 'trigger_type'], name='notificatio_tenant__24347a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_at', models.DateTimeField()),
                ('segment', models.CharField(choices=[('all_patients', 'All patients'), ('future_appointments', 'Future appointments'), ('inactive_patients', 'Inactive patients')], max_length=40)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('template_context', models.JSONField(blank=True, default=dict)),
                ('data_extra', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_notifications', to='notifications.notificationtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scheduled_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'run_at'], name='scheduled_n_tenant__695079_idx'), models.Index(fields=['run_at', 'status'], name='scheduled_n_run_at_381e3e_idx')],
            },
        ),
    ]
