# Generated by Django 5.2.12 on 2026-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_blockedperiod_professionalavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
