# Generated by Django 5.2.12 on 2026-03-26 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_clinic_addresses'),
        ('users', '0003_public_schema_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSSeller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('invite_code', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saas_sellers',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['email'], name='saas_seller_email_25e3ff_idx'), models.Index(fields=['invite_code'], name='saas_seller_invite__5603ce_idx'), models.Index(fields=['is_active'], name='saas_seller_is_acti_e4f126_idx')],
            },
        ),
        migrations.CreateModel(
            name='SaaSClinicSignupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow', models.CharField(choices=[('self_signup', 'Self signup'), ('saas_invite', 'SaaS invite')], default='self_signup', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_slug', models.SlugField(blank=True, max_length=80)),
                ('plan', models.CharField(default='starter', max_length=20)),
                ('owner_full_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('owner_tax_number', models.CharField(blank=True, max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('verification_code', models.CharField(blank=True, max_length=6)),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signup_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='tenants.tenant')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_requests', to='users.saasseller')),
            ],
            options={
                'db_table': 'saas_clinic_signup_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_email', 'status'], name='saas_clinic_owner_e_6775bb_idx'), models.Index(fields=['flow', 'status'], name='saas_clinic_flow_7a11c8_idx'), models.Index(fields=['created_at'], name='saas_clinic_created_31bdf1_idx')],
            },
        ),
    ]
