# Generated by Django 5.2.12 on 2026-03-26 18:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_saasseller_saasclinicsignuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(blank=True, max_length=32)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tutorial_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutorial_videos',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='users.tutorialvideo')),
            ],
            options={
                'db_table': 'tutorial_progress',
            },
        ),
        migrations.AddIndex(
            model_name='tutorialvideo',
            index=models.Index(fields=['is_published'], name='tutorial_vi_is_publ_6c5773_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialvideo',
            index=models.Index(fields=['order_index'], name='tutorial_vi_order_i_40f0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialvideo',
            index=models.Index(fields=['created_at'], name='tutorial_vi_created_adc699_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialprogress',
            index=models.Index(fields=['user', 'completed'], name='tutorial_pr_user_id_1d2270_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorialprogress',
            index=models.Index(fields=['updated_at'], name='tutorial_pr_updated_938c51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorialprogress',
            unique_together={('user', 'video')},
        ),
    ]
