# Generated by Django 5.2.12 on 2026-03-27 01:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tutorialvideo_tutorialprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSAISettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='grok', max_length=30)),
                ('model_name', models.CharField(default='grok-4-1-fast', max_length=80)),
                ('endpoint_url', models.URLField(default='https://api.x.ai/v1/chat/completions')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('max_tokens', models.PositiveIntegerField(default=600)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saas_ai_settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
