# Generated by Django 5.2.12 on 2026-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_saasaisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='goklinikuser',
            name='access_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
