# Generated by Django 5.2.12 on 2026-04-08 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_doctorpatientassignment'),
        ('tenants', '0005_tenantspecialty_description'),
        ('users', '0007_goklinikuser_access_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target', models.CharField(choices=[('patient', 'Patient'), ('clinic', 'Clinic')], max_length=20)),
                ('image_url', models.URLField(max_length=2048)),
                ('storage_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_image_assets', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_image_assets', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_image_assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'target'], name='uploaded_im_tenant__20a86f_idx'), models.Index(fields=['patient'], name='uploaded_im_patient_6141f2_idx'), models.Index(fields=['created_at'], name='uploaded_im_created_b6a0fe_idx')],
            },
        ),
    ]
