# Generated by Django 5.2.12 on 2026-04-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_uploadedimageasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goklinikuser',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
