# Generated by Django 5.2.12 on 2026-04-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_goklinikuser_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goklinikuser',
            name='app_installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goklinikuser',
            name='last_app_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
