# Generated by Django 5.2.12 on 2026-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_goklinikuser_app_installed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goklinikuser',
            name='temp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
