from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .dashboard_views import (
    SaaSAISettingsAPIView,
    SaaSClientDetailAPIView,
    SaaSClientsAPIView,
    SaaSDashboardAPIView,
    SaaSInviteAcceptAPIView,
    SaaSInvitePreviewAPIView,
    SaaSSellerDetailAPIView,
    SaaSSellerLookupAPIView,
    SaaSSellersAPIView,
    SaaSSignupRequestCodeAPIView,
    SaaSSignupVerifyCodeAPIView,
)
from .views import (
    ActivityLogAPIView,
    ChangePasswordAPIView,
    CurrentUserAPIView,
    CurrentUserAvatarUploadAPIView,
    ForgotPasswordAPIView,
    InviteUserAPIView,
    LoginAPIView,
    RegisterAPIView,
    TutorialDetailAPIView,
    TutorialProgressAPIView,
    TutorialsAPIView,
    TeamMemberDetailAPIView,
    TeamMembersAPIView,
)

urlpatterns = [
    path("register/", RegisterAPIView.as_view(), name="auth-register"),
    path("login/", LoginAPIView.as_view(), name="auth-login"),
    path("refresh/", TokenRefreshView.as_view(), name="auth-refresh"),
    path("forgot-password/", ForgotPasswordAPIView.as_view(), name="auth-forgot-password"),
    path("change-password/", ChangePasswordAPIView.as_view(), name="auth-change-password"),
    path("me/", CurrentUserAPIView.as_view(), name="auth-me"),
    path("me/avatar/", CurrentUserAvatarUploadAPIView.as_view(), name="auth-me-avatar"),
    path("team/", TeamMembersAPIView.as_view(), name="auth-team"),
    path("team/<uuid:member_id>/", TeamMemberDetailAPIView.as_view(), name="auth-team-detail"),
    path("activity-log/", ActivityLogAPIView.as_view(), name="auth-activity-log"),
    path("invite/", InviteUserAPIView.as_view(), name="auth-invite"),
    path("tutorials/", TutorialsAPIView.as_view(), name="auth-tutorials"),
    path("tutorials/<uuid:video_id>/", TutorialDetailAPIView.as_view(), name="auth-tutorial-detail"),
    path("tutorials/<uuid:video_id>/progress/", TutorialProgressAPIView.as_view(), name="auth-tutorial-progress"),
    path("saas/dashboard/", SaaSDashboardAPIView.as_view(), name="auth-saas-dashboard"),
    path("saas/clients/", SaaSClientsAPIView.as_view(), name="auth-saas-clients"),
    path("saas/clients/<uuid:client_id>/", SaaSClientDetailAPIView.as_view(), name="auth-saas-client-detail"),
    path("saas/sellers/", SaaSSellersAPIView.as_view(), name="auth-saas-sellers"),
    path("saas/sellers/<uuid:seller_id>/", SaaSSellerDetailAPIView.as_view(), name="auth-saas-seller-detail"),
    path("saas/settings/ai/", SaaSAISettingsAPIView.as_view(), name="auth-saas-settings-ai"),
    path("saas/signup/request-code/", SaaSSignupRequestCodeAPIView.as_view(), name="auth-saas-signup-request-code"),
    path("saas/signup/verify-code/", SaaSSignupVerifyCodeAPIView.as_view(), name="auth-saas-signup-verify-code"),
    path("saas/signup/invite/<uuid:token>/", SaaSInvitePreviewAPIView.as_view(), name="auth-saas-invite-preview"),
    path("saas/signup/invite/accept/", SaaSInviteAcceptAPIView.as_view(), name="auth-saas-invite-accept"),
    path("saas/signup/seller/<str:code>/", SaaSSellerLookupAPIView.as_view(), name="auth-saas-seller-lookup"),
]
