# Generated by Django 5.2.12 on 2026-04-08 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_travel_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='travel_plan', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'travel_plans',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('transfer_date', models.DateField()),
                ('transfer_time', models.TimeField()),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('confirmed_by_patient', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='travel_plans.travelplan')),
            ],
            options={
                'db_table': 'travel_plan_transfers',
                'ordering': ['display_order', 'transfer_date', 'transfer_time'],
            },
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('checkout_date', models.DateField()),
                ('checkout_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50)),
                ('hotel_phone', models.CharField(blank=True, max_length=50)),
                ('location_link', models.URLField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('travel_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='travel_plans.travelplan')),
            ],
            options={
                'db_table': 'travel_plan_hotels',
            },
        ),
        migrations.CreateModel(
            name='FlightInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('arrival', 'Chegada'), ('departure', 'Regresso')], max_length=20)),
                ('flight_number', models.CharField(max_length=80)),
                ('flight_date', models.DateField()),
                ('flight_time', models.TimeField()),
                ('airport', models.CharField(max_length=255)),
                ('airline', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='travel_plans.travelplan')),
            ],
            options={
                'db_table': 'travel_plan_flights',
            },
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['tenant', 'patient'], name='travel_plan_tenant__e37182_idx'),
        ),
        migrations.AddIndex(
            model_name='travelplan',
            index=models.Index(fields=['created_at'], name='travel_plan_created_5a109e_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['travel_plan', 'display_order'], name='travel_plan_travel__2793b2_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['transfer_date', 'transfer_time'], name='travel_plan_transfe_c6e7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status'], name='travel_plan_status_0e3f55_idx'),
        ),
        migrations.AddIndex(
            model_name='flightinfo',
            index=models.Index(fields=['travel_plan', 'direction'], name='travel_plan_travel__b7ef93_idx'),
        ),
        migrations.AddIndex(
            model_name='flightinfo',
            index=models.Index(fields=['flight_date', 'flight_time'], name='travel_plan_flight__b91c89_idx'),
        ),
        migrations.AddConstraint(
            model_name='flightinfo',
            constraint=models.UniqueConstraint(fields=('travel_plan', 'direction'), name='travel_plan_unique_flight_per_direction'),
        ),
    ]
