# Generated by Django 5.2.12 on 2026-04-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
