# Generated by Django 5.1.6 on 2026-03-23 15:48

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('goklinikuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('allergies', models.TextField(blank=True)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=80)),
                ('health_insurance', models.CharField(blank=True, max_length=120)),
                ('referral_source', models.CharField(choices=[('instagram', 'Instagram'), ('indication', 'Indication'), ('google', 'Google'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lead', 'Lead')], default='lead', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='tenants.tenantspecialty')),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['status'], name='patients_status_7c14f6_idx')],
            },
            bases=('users.goklinikuser',),
            managers=[
                ('objects', apps.users.models.GoKlinikUserManager()),
            ],
        ),
    ]
