# Generated by Django 5.1.6 on 2026-03-23 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=255)),
                ('surgery_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surgeries',
                'ordering': ['-surgery_date'],
            },
        ),
    ]
