# Generated by Django 5.2.12 on 2026-03-23 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_blockedperiod_professionalavailability_and_more'),
        ('patients', '0001_initial'),
        ('post_op', '0002_initial'),
        ('tenants', '0002_tenantspecialty_default_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOpJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surgery_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postop_journeys', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postop_journeys', to='patients.patient')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postop_journeys', to='tenants.tenantspecialty')),
            ],
            options={
                'db_table': 'post_op_journeys',
                'ordering': ['-surgery_date'],
            },
        ),
        migrations.CreateModel(
            name='PostOpChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('item_text', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='post_op.postopjourney')),
            ],
            options={
                'db_table': 'post_op_checklist',
                'ordering': ['day_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvolutionPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('photo_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_clinic', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='post_op.postopjourney')),
            ],
            options={
                'db_table': 'post_op_evolution_photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PostOpProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('is_milestone', models.BooleanField(default=False)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postop_protocols', to='tenants.tenantspecialty')),
            ],
            options={
                'db_table': 'post_op_protocols',
                'ordering': ['day_number', 'title'],
                'unique_together': {('specialty', 'day_number', 'title')},
            },
        ),
        migrations.DeleteModel(
            name='Surgery',
        ),
    ]
