# Generated by Django 5.2.12 on 2026-03-27 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_doctorpatientassignment'),
        ('post_op', '0003_postopjourney_postopchecklist_evolutionphoto_and_more'),
        ('tenants', '0004_tenant_ai_assistant_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentMedicalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=20)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_urgent_medical_requests', to=settings.AUTH_USER_MODEL)),
                ('assigned_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_urgent_medical_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_medical_requests', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_medical_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'urgent_medical_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='urgent_medi_tenant__1c7555_idx'), models.Index(fields=['assigned_professional', 'status'], name='urgent_medi_assigne_fc8be3_idx'), models.Index(fields=['patient', 'created_at'], name='urgent_medi_patient_af6411_idx')],
            },
        ),
    ]
