# Generated by Django 5.2.12 on 2026-04-02 15:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_clinic_location'),
        ('patients', '0002_doctorpatientassignment'),
        ('post_op', '0004_urgentmedicalrequest'),
        ('tenants', '0005_tenantspecialty_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostOperatoryCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.PositiveIntegerField()),
                ('pain_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('has_fever', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_operatory_checkins',
                'ordering': ['-day', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='postopjourney',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postop_journeys', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='postopjourney',
            name='current_day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='postopjourney',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postopjourney',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postopjourney',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='postopjourney',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient',), name='post_op_unique_active_journey_by_patient'),
        ),
        migrations.AddField(
            model_name='postoperatorycheckin',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='post_op.postopjourney'),
        ),
        migrations.AddIndex(
            model_name='postoperatorycheckin',
            index=models.Index(fields=['journey', 'day'], name='post_operat_journey_20b8aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postoperatorycheckin',
            unique_together={('journey', 'day')},
        ),
    ]
