# Generated by Django 5.2.12 on 2026-04-02 20:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_op", "0005_postoperatorycheckin_postopjourney_clinic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrgentTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="high",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("viewed", "Viewed"), ("resolved", "Resolved")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_tickets",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="urgent_tickets_as_doctor",
                        to="users.goklinikuser",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_tickets",
                        to="patients.patient",
                    ),
                ),
                (
                    "post_op_journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urgent_tickets",
                        to="post_op.postopjourney",
                    ),
                ),
            ],
            options={
                "db_table": "urgent_tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="urgentticket",
            index=models.Index(fields=["clinic", "status"], name="urgent_tick_clinic__d6b96d_idx"),
        ),
        migrations.AddIndex(
            model_name="urgentticket",
            index=models.Index(fields=["doctor", "status"], name="urgent_tick_doctor__c5407d_idx"),
        ),
        migrations.AddIndex(
            model_name="urgentticket",
            index=models.Index(fields=["patient", "created_at"], name="urgent_tick_patient_188c65_idx"),
        ),
        migrations.AddIndex(
            model_name="urgentticket",
            index=models.Index(fields=["post_op_journey", "status"], name="urgent_tick_post_op_641156_idx"),
        ),
    ]
