# Generated by Django 5.1.6 on 2026-03-23 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('primary_color', models.CharField(default='#0D5C73', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex value like #0D5C73.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary_color', models.CharField(default='#4A7C59', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex value like #0D5C73.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('accent_color', models.CharField(default='#C8992E', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex value like #0D5C73.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('favicon_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty_name', models.CharField(max_length=120)),
                ('specialty_icon', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_specialties',
                'ordering': ['display_order', 'specialty_name'],
                'unique_together': {('tenant', 'specialty_name')},
            },
        ),
    ]
