# Generated by Django 5.2.12 on 2026-03-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantspecialty',
            name='default_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
