# Generated by Django 5.2.12 on 2026-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantspecialty_default_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='clinic_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
