# Generated by Django 5.2.12 on 2026-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_clinic_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ai_assistant_prompt',
            field=models.TextField(blank=True, default='Você é a assistente virtual da clínica. Atenda com empatia, objetividade e linguagem simples. Responda somente com base no contexto do próprio paciente autenticado. Nunca revele, invente ou inferira dados de outros pacientes. Se faltar informação clínica, oriente o paciente a falar com a equipe médica.'),
        ),
    ]
