# Generated by Django 5.1.6 on 2026-03-23 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('message', 'Message'), ('call', 'Call'), ('note', 'Internal Note')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
