# Generated by Django 5.2.12 on 2026-03-27 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_message_delete_patientinteraction'),
        ('patients', '0002_doctorpatientassignment'),
        ('tenants', '0004_tenant_ai_assistant_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_ai_messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'patient_ai_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='patient_ai__patient_dd506b_idx'), models.Index(fields=['tenant', 'created_at'], name='patient_ai__tenant__724388_idx')],
            },
        ),
    ]
