# Generated by Django 5.2.12 on 2026-04-08 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_patient_ai_message_source(apps, schema_editor):
    PatientAIMessage = apps.get_model('chat', 'PatientAIMessage')
    PatientAIMessage.objects.filter(role='user').update(source='patient')
    PatientAIMessage.objects.filter(role='assistant').update(source='ai')


def revert_patient_ai_message_source(apps, schema_editor):
    PatientAIMessage = apps.get_model('chat', 'PatientAIMessage')
    PatientAIMessage.objects.update(source='ai')


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_patientaimessage'),
        ('patients', '0002_doctorpatientassignment'),
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaimessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_patient_ai_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientaimessage',
            name='source',
            field=models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI'), ('staff', 'Staff'), ('system', 'System')], default='ai', max_length=20),
        ),
        migrations.RunPython(populate_patient_ai_message_source, revert_patient_ai_message_source),
        migrations.CreateModel(
            name='TenantAIChatSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_settings', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_chat_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_ai_settings',
            },
        ),
        migrations.CreateModel(
            name='PatientAIConversationControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('force_human', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_control', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_ai_controls', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_ai_control_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_ai_conversation_controls',
                'indexes': [models.Index(fields=['tenant', 'force_human'], name='patient_ai__tenant__cbabb0_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientAITypingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_typing', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_typing_status', to='patients.patient')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_ai_typing_statuses', to='tenants.tenant')),
                ('typed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_ai_typing_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_ai_typing_status',
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='patient_ai__tenant__2cddbd_idx')],
            },
        ),
    ]
