# Generated by Django 5.2.12 on 2026-04-01 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOperatory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('diseases', models.TextField(blank=True)),
                ('smoking', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='pre_operatory_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_operatory_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pre_operatory_records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOperatoryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pre_operatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pre_operatory.preoperatory')),
            ],
            options={
                'db_table': 'pre_operatory_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='preoperatory',
            index=models.Index(fields=['tenant', 'status'], name='pre_operato_tenant__d30499_idx'),
        ),
        migrations.AddIndex(
            model_name='preoperatory',
            index=models.Index(fields=['patient', 'status'], name='pre_operato_patient_9c1dc1_idx'),
        ),
        migrations.AddConstraint(
            model_name='preoperatory',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_review', 'approved'])), fields=('patient',), name='pre_operatory_unique_active_by_patient'),
        ),
        migrations.AddIndex(
            model_name='preoperatoryfile',
            index=models.Index(fields=['pre_operatory', 'type'], name='pre_operato_pre_ope_e0f432_idx'),
        ),
    ]
