# Generated by Django 5.2.12 on 2026-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_operatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preoperatoryfile',
            name='file_url',
            field=models.URLField(max_length=2048),
        ),
    ]
