# Generated by Django 5.2.12 on 2026-04-02 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_operatory', '0002_alter_preoperatoryfile_file_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperatory',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'surgeon'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pre_operatory_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preoperatory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
