# Generated by Django 5.2.12 on 2026-04-06 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_approved_at(apps, schema_editor):
    PreOperatory = apps.get_model("pre_operatory", "PreOperatory")
    PreOperatory.objects.filter(
        status="approved",
        approved_at__isnull=True,
    ).update(approved_at=models.F("updated_at"))


def clear_backfilled_approved_at(apps, schema_editor):
    PreOperatory = apps.get_model("pre_operatory", "PreOperatory")
    PreOperatory.objects.filter(
        status="approved",
        approved_at=models.F("updated_at"),
    ).update(approved_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('pre_operatory', '0003_preoperatory_assigned_doctor_preoperatory_notes'),
        ('tenants', '0005_tenantspecialty_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOperatoryAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('patient_updated', 'Patient updated'), ('clinic_updated', 'Clinic updated'), ('file_deleted', 'File deleted')], max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pre_operatory_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='preoperatory',
            name='pre_operatory_unique_active_by_patient',
        ),
        migrations.AddField(
            model_name='preoperatory',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_approved_at, clear_backfilled_approved_at),
        migrations.AddConstraint(
            model_name='preoperatory',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'in_review'])), fields=('patient',), name='pre_operatory_unique_active_by_patient'),
        ),
        migrations.AddField(
            model_name='preoperatoryauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_operatory_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preoperatoryauditlog',
            name='pre_operatory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pre_operatory.preoperatory'),
        ),
        migrations.AddIndex(
            model_name='preoperatoryauditlog',
            index=models.Index(fields=['pre_operatory', 'created_at'], name='pre_operato_pre_ope_c353f5_idx'),
        ),
        migrations.AddIndex(
            model_name='preoperatoryauditlog',
            index=models.Index(fields=['action', 'created_at'], name='pre_operato_action_d99c6e_idx'),
        ),
    ]
