# Generated by Django 5.2.12 on 2026-04-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_operatory', '0004_preoperatoryauditlog_and_more'),
        ('tenants', '0005_tenantspecialty_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='preoperatory',
            name='procedure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_operatory_records', to='tenants.tenantspecialty'),
        ),
    ]
