// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpKdfuz3eRFvfmUoOxqPQ6kYCG_8seeY',
    appId: '1:989198183507:web:456b9893a5009e4066eaa6',
    messagingSenderId: '989198183507',
    projectId: 'goklinik-push',
    authDomain: 'goklinik-push.firebaseapp.com',
    storageBucket: 'goklinik-push.firebasestorage.app',
    measurementId: 'G-9TZ7RKPCNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZb8IFWERZPxee2-k0Usmydy3sP2DAXg',
    appId: '1:989198183507:android:15a53b06528e678166eaa6',
    messagingSenderId: '989198183507',
    projectId: 'goklinik-push',
    storageBucket: 'goklinik-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7s0xyrKzAK6MIBayJ4537hPiUgLd5k_c',
    appId: '1:989198183507:ios:b0c1bff9aebd75fa66eaa6',
    messagingSenderId: '989198183507',
    projectId: 'goklinik-push',
    storageBucket: 'goklinik-push.firebasestorage.app',
    iosBundleId: 'com.cleiton.goklinik.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7s0xyrKzAK6MIBayJ4537hPiUgLd5k_c',
    appId: '1:989198183507:ios:75f37b6bbcf13e9166eaa6',
    messagingSenderId: '989198183507',
    projectId: 'goklinik-push',
    storageBucket: 'goklinik-push.firebasestorage.app',
    iosBundleId: 'com.goklinik.goklinikMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXpKdfuz3eRFvfmUoOxqPQ6kYCG_8seeY',
    appId: '1:989198183507:web:446c3a3647d0fccb66eaa6',
    messagingSenderId: '989198183507',
    projectId: 'goklinik-push',
    authDomain: 'goklinik-push.firebaseapp.com',
    storageBucket: 'goklinik-push.firebasestorage.app',
    measurementId: 'G-ZPMZ7HWMXZ',
  );
}
